#!/bin/bash
################################################################################
#
# qit utils
# 
# Helper functions for qit
#
################################################################################

################################################################################
#
# Print:
# Logging functions
#
################################################################################
info() {
  local message
  message="${1}"

  echo "qit[info]:\t${message}"
}

error() {
  local message
  message="${1}"

  local tip
  tip="${2}"

  echo "qit[error]:\t${message}"
  echo "qit[tip]:\t${tip}"
}
